In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
sns.set_style("whitegrid")
plt.style.use("fivethirtyeight")

## Representing  text as numerical data

In [17]:
# example text as model training (sms messages)
simple_train = ['call you tonight', 'call me a cab', 'please call me', 'please call me...PLEASE']

In [18]:
# Import and instantiate CountVectorizer (with the default parameter)
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer()

# learn the 'vocabulary' of the training data (occurs in-place)
vect.fit(simple_train)

# examine the fitted vocabulary
vect.get_feature_names_out()

array(['cab', 'call', 'me', 'please', 'tonight', 'you'], dtype=object)

In [19]:
# transform training data into a 'document-term matrix'
simple_train_dtm = vect.transform(simple_train)
simple_train_dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 12 stored elements and shape (4, 6)>

In [20]:
# convert sparse matrix to a dense matrix
simple_train_dtm.toarray()

array([[0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 0],
       [0, 1, 1, 2, 0, 0]])

In [21]:
# examine the vocabulary and document-term matrix together
pd.DataFrame(simple_train_dtm.toarray(), columns = vect.get_feature_names_out())

   cab  call  me  please  tonight  you
0    0     1   0       0        1    1
1    1     1   1       0        0    0
2    0     1   1       1        0    0
3    0     1   1       2        0    0

In [22]:
# check the type of the document-term matrix
print(type(simple_train_dtm))

# examine the sparse matrix contents
print(simple_train_dtm)

<class 'scipy.sparse._csr.csr_matrix'>
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 12 stored elements and shape (4, 6)>
  Coords	Values
  (0, 1)	1
  (0, 4)	1
  (0, 5)	1
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (2, 1)	1
  (2, 2)	1
  (2, 3)	1
  (3, 1)	1
  (3, 2)	1
  (3, 3)	2

In [25]:
# example test for model testing
simple_test = ["please don't call me"]

In [26]:
# transform testing data into a document-term matrix (using exesting vocablury)
simple_test_dtm = vect.transform(simple_test)
simple_test_dtm.toarray()

array([[0, 1, 1, 1, 0, 0]])

In [27]:
# examine the vocabulary and document-term matrix together
pd.DataFrame(simple_test_dtm.toarray(), columns=vect.get_feature_names_out())

   cab  call  me  please  tonight  you
0    0     1   1       1        0    0

### Tokenization; Stop Word; Stemming; Lemitization

In [34]:
#1} Tokenization : Tokens are formed
import nltk
nltk.download("punkt_tab")#punkt sentence tokenizer tokenizes the sentence and works on unsupervised learning and can be trained on unlabeled data.
#   Word tokenization
from nltk.tokenize import word_tokenize

text = "He stepped gingerly onto the bridge knowing, that enchantment awaited on the other side.\nIt was difficult for Mary to admit; that most of her workout\n consisted of exercising poor judgment"
tokens = word_tokenize(text)
print("\nThe sentence input used is : \n\n",text)
print("\n\nThe tokenized words are \n",tokens)

The sentence input used is :

 He stepped gingerly onto the bridge knowing, that enchantment awaited on the other side.
It was difficult for Mary to admit; that most of her workout
 consisted of exercising poor judgment


The tokenized words are
 ['He', 'stepped', 'gingerly', 'onto', 'the', 'bridge', 'knowing', ',', 'that', 'enchantment', 'awaited', 'on', 'the', 'other', 'side', '.', 'It', 'was', 'difficult', 'for', 'Mary', 'to', 'admit', ';', 'that', 'most', 'of', 'her', 'workout', 'consisted', 'of', 'exercising', 'poor', 'judgment']

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [35]:
# sentence tokenizer
from nltk.tokenize import sent_tokenize

tokens_sent = sent_tokenize(text)
print("\nThe tokenized sentence are: \n",tokens_sent)

The tokenized sentence are:
 ['He stepped gingerly onto the bridge knowing, that enchantment awaited on the other side.', 'It was difficult for Mary to admit; that most of her workout\n consisted of exercising poor judgment']

In [37]:
#2} Stop Words : Common words which are often removed during nlp usage

from nltk.corpus import stopwords
nltk.download("stopwords")

#nltk.download("stopwords")

stopwords= set(stopwords.words("english"))
print(stopwords)
filtered_words = []

for w in tokens:
    if w not in stopwords:
        filtered_words.append(w)
print("\nThe stop words are removed now, Tokenized words or filtered tokenized words are : \n\n",filtered_words)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...

{"mustn't", 'here', 'd', "they're", 'during', 'so', 'it', 'some', 'theirs', 'these', 'who', 'her', 'doesn', 'she', 'up', 're', 'by', 'wasn', 'will', 's', 'that', 'a', "wasn't", "we'll", 'this', 'until', 'were', "didn't", "needn't", "shouldn't", 'yourselves', 'few', 'once', "they'll", "doesn't", 'me', 'them', 'same', 'no', 'myself', "that'll", 'was', 'weren', 'ain', 'm', "you're", "isn't", "hasn't", 'yourself', 'his', "it's", "wouldn't", 'yours', 'won', 'against', 'mustn', 'through', 'not', 'under', 'just', "he's", 'couldn', "she's", 'very', "you'll", 'both', "he'd", 'but', 'can', "mightn't", 'had', 'most', 'have', "i've", 'than', "should've", 'll', 'shan', 'shouldn', 'at', 'whom', 'themselves', 'why', 'hadn', 'am', "shan't", "it'd", 'he', "couldn't", "she'll", 'between', 'where', 'my', 'what', 'we', "hadn't", 'such', "you've", 'into', 'further', 'your', 'didn', 'for', 'those', 've', "don't", "aren't", 'as', 'doing', 'hers', "i'd", 'or', "you'd", 'himself', 'him', 'are', 'the', 'i', 'because', 'been', 'about', 'being', 'don', 'they', "we'd", 'from', 'with', 'has', "i'll", 'herself', 'own', 'on', 'needn', 'only', 'to', 'do', 'itself', 'and', 'below', 'their', 'mightn', "i'm", 'there', 'above', 'out', 'nor', 't', 'its', 'each', 'more', "we've", 'which', 'an', 'our', "weren't", 'other', 'all', 'ma', 'off', 'aren', 'when', 'you', 'while', "he'll", 'hasn', 'of', 'how', 'before', 'any', "it'll", "we're", 'after', 'then', 'did', 'having', 'does', "they've", "won't", 'too', 'y', 'ours', 'be', 'now', 'if', 'is', 'down', "she'd", 'over', 'in', "they'd", "haven't", 'ourselves', 'o', 'haven', 'should', 'wouldn', 'again', 'isn'}

The stop words are removed now, Tokenized words or filtered tokenized words are :

 ['He', 'stepped', 'gingerly', 'onto', 'bridge', 'knowing', ',', 'enchantment', 'awaited', 'side', '.', 'It', 'difficult', 'Mary', 'admit', ';', 'workout', 'consisted', 'exercising', 'poor', 'judgment']

[nltk_data]   Unzipping corpora\stopwords.zip.