In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
sns.set_style("whitegrid")
plt.style.use("fivethirtyeight")

## Representing  text as numerical data

In [4]:
# example text as model training (sms messages)
simple_train = ['call you tonight', 'call me a cab', 'please call me', 'please call me...PLEASE']

In [5]:
# Import and instantiate CountVectorizer (with the default parameter)
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer()

# learn the 'vocabulary' of the training data (occurs in-place)
vect.fit(simple_train)

# examine the fitted vocabulary
vect.get_feature_names_out()

array(['cab', 'call', 'me', 'please', 'tonight', 'you'], dtype=object)

In [6]:
# transform training data into a 'document-term matrix'
simple_train_dtm = vect.transform(simple_train)
simple_train_dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 12 stored elements and shape (4, 6)>

In [7]:
# convert sparse matrix to a dense matrix
simple_train_dtm.toarray()

array([[0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 0],
       [0, 1, 1, 2, 0, 0]])

In [8]:
# examine the vocabulary and document-term matrix together
pd.DataFrame(simple_train_dtm.toarray(), columns = vect.get_feature_names_out())

   cab  call  me  please  tonight  you
0    0     1   0       0        1    1
1    1     1   1       0        0    0
2    0     1   1       1        0    0
3    0     1   1       2        0    0

In [9]:
# check the type of the document-term matrix
print(type(simple_train_dtm))

# examine the sparse matrix contents
print(simple_train_dtm)

<class 'scipy.sparse._csr.csr_matrix'>
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 12 stored elements and shape (4, 6)>
  Coords	Values
  (0, 1)	1
  (0, 4)	1
  (0, 5)	1
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (2, 1)	1
  (2, 2)	1
  (2, 3)	1
  (3, 1)	1
  (3, 2)	1
  (3, 3)	2

In [10]:
# example test for model testing
simple_test = ["please don't call me"]

In [11]:
# transform testing data into a document-term matrix (using exesting vocablury)
simple_test_dtm = vect.transform(simple_test)
simple_test_dtm.toarray()

array([[0, 1, 1, 1, 0, 0]])

In [12]:
# examine the vocabulary and document-term matrix together
pd.DataFrame(simple_test_dtm.toarray(), columns=vect.get_feature_names_out())

   cab  call  me  please  tonight  you
0    0     1   1       1        0    0

### Tokenization; Stop Word; Stemming; Lemitization

In [13]:
#1} Tokenization : Tokens are formed
import nltk
nltk.download("punkt_tab")#punkt sentence tokenizer tokenizes the sentence and works on unsupervised learning and can be trained on unlabeled data.
#   Word tokenization
from nltk.tokenize import word_tokenize

text = "He stepped gingerly onto the bridge knowing, that enchantment awaited on the other side.\nIt was difficult for Mary to admit; that most of her workout\n consisted of exercising poor judgment"
tokens = word_tokenize(text)
print("\nThe sentence input used is : \n\n",text)
print("\n\nThe tokenized words are \n",tokens)

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

The sentence input used is :

 He stepped gingerly onto the bridge knowing, that enchantment awaited on the other side.
It was difficult for Mary to admit; that most of her workout
 consisted of exercising poor judgment


The tokenized words are
 ['He', 'stepped', 'gingerly', 'onto', 'the', 'bridge', 'knowing', ',', 'that', 'enchantment', 'awaited', 'on', 'the', 'other', 'side', '.', 'It', 'was', 'difficult', 'for', 'Mary', 'to', 'admit', ';', 'that', 'most', 'of', 'her', 'workout', 'consisted', 'of', 'exercising', 'poor', 'judgment']

In [14]:
# sentence tokenizer
from nltk.tokenize import sent_tokenize

tokens_sent = sent_tokenize(text)
print("\nThe tokenized sentence are: \n",tokens_sent)

The tokenized sentence are:
 ['He stepped gingerly onto the bridge knowing, that enchantment awaited on the other side.', 'It was difficult for Mary to admit; that most of her workout\n consisted of exercising poor judgment']

In [15]:
#2} Stop Words : Common words which are often removed during nlp usage

from nltk.corpus import stopwords
nltk.download("stopwords")

#nltk.download("stopwords")

stopwords= set(stopwords.words("english"))
print(stopwords)
filtered_words = []

for w in tokens:
    if w not in stopwords:
        filtered_words.append(w)
print("\nThe stop words are removed now, Tokenized words or filtered tokenized words are : \n\n",filtered_words)

{'those', 'just', "you're", 'yours', "it's", 'mightn', "didn't", 'themselves', 'itself', 'to', 'his', 'hadn', "i'll", "they've", 'have', 'below', 'as', 'him', 'in', "don't", "you'll", "wouldn't", 'further', 'an', 'me', 'not', 'but', 'here', 'won', 'your', 'off', 'about', 'so', "haven't", 'haven', "doesn't", 'its', "we've", 'shouldn', 'through', 'being', 'and', 'had', 'when', 'aren', 'o', "she'd", 'she', 'now', 'should', 'will', 'weren', 'up', "we'd", 'by', "it'd", 'doing', "shan't", "that'll", "weren't", 'been', 'ourselves', "couldn't", 'hers', 'we', 'over', 'wouldn', 'isn', 'because', 'such', 'against', 'few', 'which', 'why', "you'd", 'each', 'for', 'be', 'it', 'our', 'd', 'herself', 'nor', 'this', 'very', 'under', "they're", 'don', 'my', 'himself', "he'll", "she's", "you've", 'what', 'yourselves', 'are', "shouldn't", "isn't", 'some', 'having', 'other', 're', "wasn't", 'all', 'did', 'too', 'her', "won't", 'the', 'am', 'he', "it'll", 'hasn', "i'd", 'them', 'again', 'on', 'if', 'than', "aren't", 'with', 'their', 'they', "we're", 'between', 'where', "hasn't", 'needn', 'at', "we'll", 'no', "he'd", "i'm", 'before', 'there', 'only', 'above', 'own', "needn't", 'of', 'any', 'you', 'does', 'during', "should've", 'then', "they'd", "mustn't", 'is', 'out', 'didn', 'i', "he's", 'these', 'doesn', 'that', 'how', 'down', 'most', 'y', 'once', "she'll", 'while', 's', "they'll", 'was', 'll', "i've", 've', "mightn't", 'into', 'couldn', 'were', 'ours', 'do', "hadn't", 'm', 'until', 'whom', 'both', 'from', 'or', 'ma', 'mustn', 'can', 'theirs', 'a', 'who', 'yourself', 'more', 'has', 'wasn', 'same', 'myself', 't', 'ain', 'shan', 'after'}

The stop words are removed now, Tokenized words or filtered tokenized words are :

 ['He', 'stepped', 'gingerly', 'onto', 'bridge', 'knowing', ',', 'enchantment', 'awaited', 'side', '.', 'It', 'difficult', 'Mary', 'admit', ';', 'workout', 'consisted', 'exercising', 'poor', 'judgment']

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [23]:
#3} Stemming : Reduces the words to their root form or base form
from nltk.stem import PorterStemmer
words = ["Organization","Organizational","Factual","running"]
#   list item stemming
stem_li = []
ps = PorterStemmer()
for i in words:
    stem_li.append(ps.stem(i))

print("The stemmed list items are: \t",stem_li)

The stemmed list items are: 	 ['organ', 'organiz', 'factual', 'run']

In [17]:
#   Stemming for words on word tokens
print(tokens)
stem_words = []
for i in tokens:
    stem_words.append(ps.stem(i))

print("\nThe stemmed list of tokenized words are : \t",stem_words)

['He', 'stepped', 'gingerly', 'onto', 'the', 'bridge', 'knowing', ',', 'that', 'enchantment', 'awaited', 'on', 'the', 'other', 'side', '.', 'It', 'was', 'difficult', 'for', 'Mary', 'to', 'admit', ';', 'that', 'most', 'of', 'her', 'workout', 'consisted', 'of', 'exercising', 'poor', 'judgment']

The stemmed list of tokenized words are : 	 ['he', 'step', 'gingerli', 'onto', 'the', 'bridg', 'know', ',', 'that', 'enchant', 'await', 'on', 'the', 'other', 'side', '.', 'it', 'wa', 'difficult', 'for', 'mari', 'to', 'admit', ';', 'that', 'most', 'of', 'her', 'workout', 'consist', 'of', 'exercis', 'poor', 'judgment']

In [18]:
#   Stemming for senteces on sentenced tokens
print(tokens_sent)
stem_sentence = []
for i in tokens_sent:
    stem_sentence.append(ps.stem(i))

print("The stemmed list of tokenized sentence are : \t",stem_sentence)

['He stepped gingerly onto the bridge knowing, that enchantment awaited on the other side.', 'It was difficult for Mary to admit; that most of her workout\n consisted of exercising poor judgment']
The stemmed list of tokenized sentence are : 	 ['he stepped gingerly onto the bridge knowing, that enchantment awaited on the other side.', 'it was difficult for mary to admit; that most of her workout\n consisted of exercising poor judg']

In [19]:
#4} Lemmatization : Breaks the words into simpler forms and makes meaning full words unlike stemming
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...

True

In [24]:
wl=WordNetLemmatizer()

#   list item lemmitization
lemma_li=[]
for i in words:
    lemma_li.append(wl.lemmatize(i))

print("The lemmatized words of the list are : \t",lemma_li)

The lemmatized words of the list are : 	 ['Organization', 'Organizational', 'Factual', 'running']

In [25]:
lemma_words = []
for i in tokens:
    lemma_words.append(wl.lemmatize(i))

print("The lemmatized word of the sentence words tokens will be: \n",lemma_words)

The lemmatized word of the sentence words tokens will be:
 ['He', 'stepped', 'gingerly', 'onto', 'the', 'bridge', 'knowing', ',', 'that', 'enchantment', 'awaited', 'on', 'the', 'other', 'side', '.', 'It', 'wa', 'difficult', 'for', 'Mary', 'to', 'admit', ';', 'that', 'most', 'of', 'her', 'workout', 'consisted', 'of', 'exercising', 'poor', 'judgment']

In [26]:
lemma_sentence = []
for i in tokens_sent:
    lemma_sentence.append(wl.lemmatize(i))

print("The lemmatized word of the sentence words tokens will be of the paragraph is : \n",lemma_sentence)

The lemmatized word of the sentence words tokens will be of the paragraph is :
 ['He stepped gingerly onto the bridge knowing, that enchantment awaited on the other side.', 'It was difficult for Mary to admit; that most of her workout\n consisted of exercising poor judgment']

In [28]:
from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer
#create an object of class PorterStemmer
porter = PorterStemmer()
lancaster=LancasterStemmer()
#provide a word to be stemmed
print("Porter Stemmer")
print("cats => ",porter.stem("cats"))
print("trouble => ",porter.stem("trouble"))
print("troubling =>", porter.stem("troubling"))
print("troubled => ",porter.stem("troubled"))
print("better => ",lancaster.stem("better"))
print("best => ",lancaster.stem("best"))
print("Lancaster Stemmer")
print("cats => ",lancaster.stem("cats"))
print("trouble => ",lancaster.stem("trouble"))
print("troubling =>",lancaster.stem("troubling"))
print("troubled => ",lancaster.stem("troubled"))
print("better => ",lancaster.stem("better"))
print("best => ",lancaster.stem("best"))

Porter Stemmer
cats =>  cat
trouble =>  troubl
troubling => troubl
troubled =>  troubl
better =>  bet
best =>  best
Lancaster Stemmer
cats =>  cat
trouble =>  troubl
troubling => troubl
troubled =>  troubl
better =>  bet
best =>  best

#### Stemming a complete sentence

In [29]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [30]:
from nltk.tokenize import sent_tokenize, word_tokenize
def stemSentence(sentence):
    token_words=word_tokenize(sentence)
    token_words
    stem_sentence=[]
    for word in token_words:
        stem_sentence.append(porter.stem(word))
        stem_sentence.append(" ")
    return "".join(stem_sentence)

sentence="Pythoners are very intelligent and work very pythonly and now they are pythoning their way to success."
x=stemSentence(sentence)
print(sentence)
print(x)

Pythoners are very intelligent and work very pythonly and now they are pythoning their way to success.
python are veri intellig and work veri pythonli and now they are python their way to success .

## Lemmatization

Stemming usually refers to a crude heuristic process that chops off the ends of words in the hope of achieving this goal correctly most of the time, and often includes the removal of derivational affixes.

Lemmatization usually refers to doing things properly with the use of a vocabulary and morphological analysis of words, normally aiming to remove inflectional endings only and to return the base or dictionary form of a word, which is known as the lemma. If confronted with the token saw, stemming might return just s, whereas lemmatization would attempt to return either see or saw depending on whether the use of the token was as a verb or a noun.

For example, runs, running, ran are all forms of the word run, therefore run is the lemma of all these words. Because lemmatization returns an actual word of the language, it is used where it is necessary to get valid words.

Python NLTK provides WordNet Lemmatizer that uses the WordNet Database to lookup lemmas of words.

In [31]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [32]:
import nltk
from nltk.stem import WordNetLemmatizer

wordnet_lemmatizer = WordNetLemmatizer()

sentence = "He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun."
punctuations = "?:!.,;"

sentence_words = nltk.word_tokenize(sentence)

for word in sentence_words:
    if word in punctuations:
        sentence_words.remove(word)

sentence_words

print("{0:20}{1:20}".format("Word", "Lemma"))

for word in sentence_words:
    print("{0:20}{1:20}".format(word, wordnet_lemmatizer.lemmatize(word)))

Word                Lemma
He                  He
was                 wa
running             running
and                 and
eating              eating
at                  at
same                same
time                time
He                  He
has                 ha
bad                 bad
habit               habit
of                  of
swimming            swimming
after               after
playing             playing
long                long
hours               hour
in                  in
the                 the
Sun                 Sun